image: alpine:latest

pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r * .public
  - mv .public public
  - ls "public/website"
  artifacts:
    paths:
    - public
  only:
  - master
